os: linux
dist: xenial
language: cpp
compiler: gcc
sudo: false

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code  


notifications:
  email:
    recipients:
      - crank5day@gmail.com
    on_success: never
on_failure: never 
